version: 2
jobs:
  build:
    docker:
       - image: alpine/git
    working_directory: /robo-drupal
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Generate documentation
          command: |
            apk add doxygen graphviz
            doxygen robo-drupalDoxygenConfig
            git config --global user.email "dev-team@thinkshout.com"
            git config --global user.name "Circle CI"
            git add .
            git commit -m "doxygen docs update for robo-drupal [ci skip]"
            git push
