version: 2
jobs:
  build:
    docker:
       - image: alpine/git
    working_directory: /robo-drupal
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - "82:35:ca:6b:5d:24:40:ab:00:8e:46:a9:51:37:2e:a3"
      - run:
          name: Generate documentation
          command: |
            apk add doxygen graphviz
            doxygen robo-drupalDoxygenConfig
            mv docs/html/* docs
            git config --global user.email "dev-team@thinkshout.com"
            git config --global user.name "Circle CI"
            git add .
            git commit -m "doxygen docs update for robo-drupal [ci skip]"
            git push --set-upstream origin $CIRCLE_BRANCH
