version: 2
jobs:
  build:
    docker:
       - image: tsgkadot/docker-doxygen
    working_directory: /var/www/html/robo-drupal
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Generate documentation
          command: |
            doxygen robo-drupalDoxygenConfig
            git add .
            git commit -m "doxygen docs update for robo-drupal [ci skip]"
            git push
